name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-pwd-test-job:
    uses: ./.github/workflows/ml2.yml
    with:
      config-path: '.github/workflows/ci.yml'
  call-build-test-job:
    uses: ./.github/workflows/ml1.yml
    with:
      config-path: '.github/workflows/ci.yml'